// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wofost
NumericMatrix wofost(List crop, DataFrame weather, List soil, List control);
RcppExport SEXP Rwofost_wofost(SEXP cropSEXP, SEXP weatherSEXP, SEXP soilSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crop(cropSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type weather(weatherSEXP);
    Rcpp::traits::input_parameter< List >::type soil(soilSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(wofost(crop, weather, soil, control));
    return __result;
END_RCPP
}
