// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lintul3
NumericMatrix lintul3(List crop, DataFrame weather, List soil, List control);
RcppExport SEXP LINTUL_lintul3(SEXP cropSEXP, SEXP weatherSEXP, SEXP soilSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crop(cropSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type weather(weatherSEXP);
    Rcpp::traits::input_parameter< List >::type soil(soilSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(lintul3(crop, weather, soil, control));
    return __result;
END_RCPP
}
// lintul0
NumericMatrix lintul0(List crop, DataFrame weather, List control);
RcppExport SEXP LINTUL_lintul0(SEXP cropSEXP, SEXP weatherSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crop(cropSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type weather(weatherSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(lintul0(crop, weather, control));
    return __result;
END_RCPP
}
// lintul1
NumericMatrix lintul1(List crop, DataFrame weather, List control);
RcppExport SEXP LINTUL_lintul1(SEXP cropSEXP, SEXP weatherSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crop(cropSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type weather(weatherSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(lintul1(crop, weather, control));
    return __result;
END_RCPP
}
// lintul2
NumericMatrix lintul2(List crop, DataFrame weather, List soil, List control);
RcppExport SEXP LINTUL_lintul2(SEXP cropSEXP, SEXP weatherSEXP, SEXP soilSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crop(cropSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type weather(weatherSEXP);
    Rcpp::traits::input_parameter< List >::type soil(soilSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(lintul2(crop, weather, soil, control));
    return __result;
END_RCPP
}
