# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lintul3 <- function(crop, weather, soil, control) {
    .Call('LINTUL_lintul3', PACKAGE = 'LINTUL', crop, weather, soil, control)
}

lintul0 <- function(crop, weather, control) {
    .Call('LINTUL_lintul0', PACKAGE = 'LINTUL', crop, weather, control)
}

lintul1 <- function(crop, weather, control) {
    .Call('LINTUL_lintul1', PACKAGE = 'LINTUL', crop, weather, control)
}

lintul2 <- function(crop, weather, soil, control) {
    .Call('LINTUL_lintul2', PACKAGE = 'LINTUL', crop, weather, soil, control)
}

